[project]
name = "xhh-auto"
version = "0.0.1"
description = "小红狐自动化"
dependencies = [
  "playwright==1.56.0",
  "Flask==3.1.2",
  "flask_cors==6.0.1",
  "waitress==3.0.2",
]

[tool.setuptools]
packages = ["小红狐"]
